# Generated by Django 4.0.2 on 2022-02-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='message',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='subject',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
