# Generated by Django 4.0.2 on 2022-03-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='prouct_price',
            new_name='product_price',
        ),
    ]
