# Generated by Django 4.0.2 on 2022-03-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_prouct_price_cart_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
