# Generated by Django 4.0.3 on 2022-03-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_cart_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
